name: Build and Execute Unit Tests

on: 
  push:
    branches: 
      - test
  pull_request:
    branches:
      - test

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet 
      run: dotnet build --configuration Release
    - name: Run pester test using invoke-gehrkin
      run: Invoke-Gherkin
