name: Build and Execute Unit Tests

on: 
  push:
    branches: 
      - test
  pull_request:
    branches:
      - test

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Run pester test using invoke-gehrkin
      run: Invoke-Gherkin
